server:
  port: 9999 
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/passowordcreater?useSSL=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456 
    hikari:
      maximum-pool-size: 10 #连接池最大连接数
      minimum-idle: 0 #允许的最小空闲属
      idle-timeout: 180000 
      connection-test-query: select 1 
      jpa:
        database: mysql
        hibernate:
        ddl-auto: create
          # ddl-auto: update
        show-sql: true
management:
  port: 9001
  security:
    enabled: false
